name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Docker login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      run: |
        TIMESTAMP=$(date +%s)
        IMAGE_NAME=my-image-name:$TIMESTAMP
        echo "Construyendo imagen..."
        docker build . --file Dockerfile --tag $IMAGE_NAME
        docker tag $IMAGE_NAME my-image-name:latest
        echo "Pusheando imagen..."
        docker push $IMAGE_NAME
        docker push my-image-name:latest
        echo "¡Imagen pusheada exitosamente!"
